#Robot laser tag game
#James Guo
#Autmn 2016
#Makefile for tank files 
all: tank_reciever tank_sender

tank_reciever: tank_reciever.c
	gcc -o tank_reciever tank_reciever.c

tank_sender: tank_sender.c
	gcc -o tank_sender tank_sender.c